CREATE TABLE IF NOT EXISTS pessoas (
  id BIGINT PRIMARY KEY,
  nome VARCHAR(120) NOT NULL,
  cpf VARCHAR(14) NOT NULL UNIQUE,
  entrou BOOLEAN NOT NULL DEFAULT FALSE,
  horario VARCHAR(8) NOT NULL DEFAULT '',
  data_entrada VARCHAR(10) NOT NULL DEFAULT '',
  timestamp_entrada TIMESTAMPTZ NULL,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS pessoas_nome_idx ON pessoas (nome);
